version: "3"

services:
  ss:
    container_name: aioshadowsocks
    image: registry.cn-hangzhou.aliyuncs.com/vpc123/aioshadowsocks:code
    network_mode: host
    restart: always
    environment:
      SS_API_ENDPOINT: ""
      SS_LOG_LEVEL: "info"
      SS_SYNC_TIME: 60
      SS_GRPC_HOST: "127.0.0.1"
      SS_GRPC_PORT: 5000
      SS_METRICS_PORT: 9888
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
    # volumes:
    # - .:/src/aioshadowsocks
    working_dir: /src/aioshadowsocks
    command: python server.py
